name: CI

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install
        run: npm ci --legacy-peer-deps
      - name: Format check
        run: npm run format:check
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
