name: CI

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Install
        run: npm ci --legacy-peer-deps
      - name: Format check
        run: npm run format:check
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Commit build
        if: startsWith(github.ref, 'refs/tags/v')
        uses: endbug/add-and-commit@v4
        with:
          add: build
          force: true
          message: Add build code
          ref: v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
